export type AdminNavItem = {
  href: string;
  label: string;
  roles: Array<"ADMIN" | "STAFF" | "ACCOUNTANT">;
  icon?: "users" | "dollar" | "shield" | "book" | "clipboard" | "package";
  isRight?: boolean;
};

export const ADMIN_NAV_ITEMS: AdminNavItem[] = [
  {
    href: "/admin",
    label: "Admin Dashboard",
    icon: "package",
    roles: ["ADMIN", "STAFF", "ACCOUNTANT"],
  },
  {
    href: "/admin/dashboard",
    label: "Dashboard",
    icon: "package",
    roles: ["ADMIN", "STAFF", "ACCOUNTANT"],
  },
  {
    href: "/admin/orders",
    label: "Orders/Payments",
    icon: "dollar",
    roles: ["ADMIN", "STAFF"],
  },
  {
    href: "/admin/orders/otc",
    label: "OTC Sales",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF", "ACCOUNTANT"],
  },
  {
    href: "/admin/b2b/procurement",
    label: "B2B Procurement",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF", "ACCOUNTANT"],
  },
  {
    href: "/admin/b2b/tenders",
    label: "B2B Tenders",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF"],
  },
  {
    href: "/admin/b2b/procurement/analytics",
    label: "B2B Procurement Analytics",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF", "ACCOUNTANT"],
  },
  {
    href: "/admin/otc/shift-close",
    label: "OTC Shift Close",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF", "ACCOUNTANT"],
  },
  {
    href: "/admin/delivery/dispatch",
    label: "Delivery Dispatch",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF"],
  },
  {
    href: "/admin/delivery/collection-review",
    label: "Delivery Collection Review",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF", "ACCOUNTANT"],
  },
  {
    href: "/admin/delivery/reconciliation/settlements",
    label: "Delivery Settlements",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF", "ACCOUNTANT"],
  },
  {
    href: "/admin/delivery/pod-report",
    label: "Delivery POD Report",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF", "ACCOUNTANT"],
  },
  {
    href: "/admin/products",
    label: "Products",
    icon: "package",
    roles: ["ADMIN", "STAFF"],
  },
  {
    href: "/admin/inventory",
    label: "Inventory",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF", "ACCOUNTANT"],
  },
  {
    href: "/admin/movements",
    label: "Movements",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF"],
  },
  {
    href: "/admin/returns",
    label: "Returns & RMA",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF"],
  },
  {
    href: "/admin/inventory-planning",
    label: "Inventory Planning",
    icon: "clipboard",
    roles: ["ADMIN", "STAFF"],
  },
  {
    href: "/admin/inventory-lots",
    label: "Inventory Lots",
    icon: "clipboard",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/stock-adjustments",
    label: "Stock Adjustments",
    icon: "clipboard",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/customers",
    label: "Customers",
    icon: "users",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/users",
    label: "Users & Roles",
    icon: "users",
    roles: ["ADMIN"],
  },
  { href: "/admin/hr", label: "HR", icon: "users", roles: ["ADMIN"] },
  {
    href: "/admin/hr/settings",
    label: "HR Settings",
    icon: "clipboard",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/suppliers",
    label: "Suppliers",
    icon: "clipboard",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/suppliers/performance",
    label: "Supplier performance",
    icon: "clipboard",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/profit-loss",
    label: "Profit & Loss",
    icon: "clipboard",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/analytics/stockout-impact",
    label: "Stockout impact",
    icon: "clipboard",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/purchases",
    label: "Purchases",
    icon: "clipboard",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/supplier-payments",
    label: "Supplier Payments",
    icon: "dollar",
    roles: ["ADMIN", "ACCOUNTANT"],
  },
  {
    href: "/admin/expenses",
    label: "Expenses",
    icon: "dollar",
    roles: ["ADMIN", "ACCOUNTANT"],
  },
  {
    href: "/admin/accounting",
    label: "Accounting",
    icon: "clipboard",
    roles: ["ADMIN", "ACCOUNTANT"],
  },
  {
    href: "/admin/accounting/aging",
    label: "AR/AP Aging",
    icon: "clipboard",
    roles: ["ADMIN", "ACCOUNTANT"],
  },
  {
    href: "/admin/accounting/reconcile",
    label: "Reconcile Totals",
    icon: "clipboard",
    roles: ["ADMIN", "ACCOUNTANT"],
  },
  {
    href: "/admin/accounting/reconciliations",
    label: "Reconciliations",
    icon: "clipboard",
    roles: ["ADMIN", "ACCOUNTANT"],
  },
  {
    href: "/admin/accounting/banks",
    label: "Banks",
    icon: "clipboard",
    roles: ["ADMIN", "ACCOUNTANT"],
  },
  {
    href: "/admin/health",
    label: "Health Check",
    icon: "shield",
    roles: ["ADMIN", "ACCOUNTANT"],
  },
  {
    href: "/admin/health/incidents",
    label: "Health Incidents",
    icon: "shield",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/resilience",
    label: "Platform Resilience",
    icon: "shield",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/guide",
    label: "Admin Guide",
    icon: "book",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/import-export",
    label: "Import/Export",
    icon: "clipboard",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/audit",
    label: "Audit Log",
    icon: "clipboard",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/audit/retention",
    label: "Retention",
    icon: "clipboard",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/audit/settings",
    label: "Audit Settings",
    icon: "clipboard",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/payments/momo",
    label: "MoMo Payments",
    icon: "dollar",
    roles: ["ADMIN"],
    isRight: true,
  },
  {
    href: "/admin/settings/communications",
    label: "Comms",
    icon: "book",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/settings/homepage",
    label: "Homepage",
    icon: "book",
    roles: ["ADMIN"],
  },
  {
    href: "/admin/settings/features",
    label: "Features",
    icon: "book",
    roles: ["ADMIN"],
  },
];

export const ADMIN_NAV_ESSENTIAL_HREFS = [
  "/admin/dashboard",
  "/admin/orders",
  "/admin/orders/otc",
  "/admin/b2b/procurement",
  "/admin/b2b/tenders",
  "/admin/b2b/procurement/analytics",
  "/admin/otc/shift-close",
  "/admin/delivery/dispatch",
  "/admin/delivery/collection-review",
  "/admin/delivery/reconciliation/settlements",
  "/admin/delivery/pod-report",
  "/admin/customers",
  "/admin/products",
  "/admin/inventory-planning",
  "/admin/inventory-lots",
  "/admin/stock-adjustments",
  "/admin/suppliers",
  "/admin/users",
  "/admin/hr",
  "/admin/hr/settings",
  "/admin/accounting",
  "/admin/import-export",
  "/admin/audit",
  "/admin/audit/retention",
  "/admin/audit/settings",
  "/admin/guide",
  "/admin/payments/momo",
  "/admin/settings/communications",
  "/admin/settings/homepage",
  "/admin/settings/features",
];

export const ADMIN_NAV_GROUPS: Array<{ label: string; hrefs: string[] }> = [
  {
    label: "Dashboard",
    hrefs: ["/admin/dashboard"],
  },
  {
    label: "Sales",
    hrefs: [
      "/admin/orders",
      "/admin/orders/otc",
      "/admin/b2b/procurement",
      "/admin/b2b/tenders",
      "/admin/b2b/procurement/analytics",
      "/admin/otc/shift-close",
    ],
  },
  {
    label: "Delivery",
    hrefs: [
      "/admin/delivery/dispatch",
      "/admin/delivery/collection-review",
      "/admin/delivery/reconciliation/settlements",
      "/admin/delivery/pod-report",
    ],
  },
  {
    label: "Inventory",
    hrefs: [
      "/admin/products",
      "/admin/inventory",
      "/admin/movements",
      "/admin/returns",
      "/admin/inventory-planning",
      "/admin/inventory-lots",
      "/admin/stock-adjustments",
    ],
  },
  {
    label: "Customers",
    hrefs: ["/admin/customers"],
  },
  {
    label: "Finance",
    hrefs: [
      "/admin/accounting",
      "/admin/accounting/aging",
      "/admin/accounting/reconcile",
      "/admin/accounting/reconciliations",
      "/admin/accounting/banks",
      "/admin/profit-loss",
      "/admin/expenses",
      "/admin/purchases",
      "/admin/supplier-payments",
      "/admin/payments/momo",
    ],
  },
  {
    label: "People",
    hrefs: [
      "/admin/users",
      "/admin/hr",
      "/admin/hr/settings",
      "/admin/suppliers",
      "/admin/suppliers/performance",
    ],
  },
  {
    label: "Analytics",
    hrefs: ["/admin/analytics/stockout-impact"],
  },
  {
    label: "System",
    hrefs: [
      "/admin/health",
      "/admin/health/incidents",
      "/admin/resilience",
      "/admin/audit",
      "/admin/audit/retention",
      "/admin/audit/settings",
      "/admin/import-export",
      "/admin/settings/communications",
      "/admin/settings/homepage",
      "/admin/settings/features",
      "/admin/guide",
    ],
  },
];
