export const IMPORT_TEMPLATES: Record<string, string[]> = {
  products: [
    "name",
    "sku",
    "category",
    "price",
    "cost",
    "minMarginPct",
    "stock",
    "supplier",
    "leadTimeDays",
    "minOrderQty",
    "packSize",
    "requiresLotTracking",
    "requiresExpiryDate",
  ],
  suppliers: ["name", "email", "phone", "leadTimeDays", "minOrderQty", "packSize", "status", "notes"],
  customers: ["name", "email", "phone", "company", "address", "creditLimit"],
  orders: ["invoiceNumber", "customerEmail", "date", "status", "total", "amountPaid", "deliveryStatus"],
  purchases: ["productSku", "supplier", "quantity", "unitCost", "status", "expectedAt", "notes"],
  inventoryLots: ["productSku", "batchCode", "expiryDate", "quantity", "receivedAt", "supplier"],
  payments: ["orderInvoice", "amount", "method", "provider", "status", "createdAt"],
  supplierPayments: [
    "supplier",
    "purchaseId",
    "amount",
    "method",
    "reference",
    "status",
    "paidAt",
    "approvedAt",
    "createdAt",
  ],
  bankTransactions: [
    "bankName",
    "postedAt",
    "amount",
    "type",
    "description",
    "reference",
  ],
};

