ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

offline: false

storeDir: C:\Users\bedel\AppData\Local\pnpm\store\v10
