-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "amountPaid" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "balance" DECIMAL(65,30) NOT NULL DEFAULT 0,
ALTER COLUMN "total" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "status" SET DEFAULT 'UNPAID';
